### ISSUE TITLE
MAC用户如何使用呢

### ISSUE THREAD

**Issue by wjfjfm** [topling/topling-alpha-test-helper#2]
可否做一个控制台的网页端

**Comment by luantian-terark** [comment]
mac用户请安装windows虚拟机后使用，或者参照教程手动并网。
网页端存在包括钓鱼在内的各种潜在的安全性问题，用户的AccessKey和AccessSecret相当于阿里云用户密码+验证码，因此请求操作必须在本地执行不能上传。
发布的辅助程序具有数字签名，请保护好自己的AccessKey与AccessSecret。并网完成后可以删除秘钥。
